---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: k8snginxappsotkust
  namespace: fluxcd-test
spec:
  interval: 15s
  path: ./deploy
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8snginxappsot
