apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: fluxgithubprovider
  namespace: fluxcd-test
spec:
  type: github
  address: https://github.com/mkamran1411/k8s_nginxapp_sot
  secretRef:
    name: github
