apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github
  namespace: fluxcd-test
spec:
  encryptedData:
    token: AgCd2Ad/Rfx7jKi1lxL3h93AsZnDEUyeaPmsy4OWvnZCuSB2fNFZWlTwKTMXLAsBbLgDWZ21jOXp/3jmQgPnNxIcWv4HXvvzT0AviLoCrYMn5FR31Dj4cHU/ZZOmQVS3YhTxjlembVoLCqzU0JkaVGcDS/WbEXQHJZUEbfusmSaYAmIgJP6bp1oXBj+wK+O78weIgcaWbpvQ4kEyBVzJQHpIuF4iNi4gOGlL7OsUQPfoV5nd3UpYGzSgmMsueW1PBjsmV6flUW+43utdfwXTryBNkQYXA8/r0r7PmsM/WWcV94HnHMJFWHfmZW04xsXGkZ89OkpLNEoE6tbYTKYhqBW1qq2Gn+lXOWzl+qpUgq7JXkYqK3f6gaQFSk4KgbgFNmDH+xRpTGrsnzFDZ0HRGfpEM4pRfvLIeGflPmlIIhDlcvg12jh8tJVeodwAfydom77EKFr2muAetWFcwFbeTwanl12YOe9KJe2J9pXY8NIM4yj4ra6quwtC/ShcFdHYWllpv2MCtrZKEk4R1yXgRcC1uOP2v21X6RdUOUf4qI++QXVyncG88D6s0bjFqXFJsLdqeBhPfZc9wlbFFdE18jReMapS/9e2kCY89O+5etOZuGpIsyvrdYZvRiX9+Y0Wmr8VAx30HefxsnAYx2rFv2hFKxZhdGixOCWYbdoqbSdl9TiN9mDvMiVMzqXxor6QjtcYCqqeetUNQYsQ72hg+UwNGg8klvX6+o6gqVwZ9CM886aFsM5dYGXv
  template:
    metadata:
      creationTimestamp: null
      name: github
      namespace: fluxcd-test

