apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github
  namespace: flux-system
spec:
  encryptedData:
    token: AgCbuKTxFSZH+CSHHRomvZduS7knCsR1ADwgWvmYz3KcKXEkzCPzIMUECGQgtyqu2dfMtF4RXVrbYlkf+NVPUvLKO21AYZy+p6+nOVRE0m8cRUaObefxgTuv4Q1hykzCFs21apaGk3XofBxWOE5huzttCj8DxMz9UmiRZowEDMYJsDoilXQ0RaS395gkkliaLWaCKZ8tntpJBn2AIONmnIxsi6vLCHxT28h1inhj9ktPO7Tckcv9+RlGy9FTiwJdcMa1V906gOdsheMAjnQ3zgIXCXpp8Xe1DYCIXVDe1bws5JQ2EXqy38h9Q7K6pLbIYBnmJa6oyF4PUWPVGGk2dNgntfr/AY+acqV6EGBBo2pYBdU7G44Up2s9rYjsxV6ckbQLBb4yAskpMFQzNgbRg5M/3/ygL9vQ5GsEDEFqQvX6wqMf/npUSg5lNotucYDh3qAhFgEmqLsJtTNbVHBTY1RNeVche+xEhBPZsebneatQstwJFIh7YAMdxHPmM4zgiqjSTZu7uRKxZIz2/w4S+pYHIbyEJI0C5TQD0Ym1VZNgkSzKBhiD/kpl8kPfzXUMuDFBcuu+GlI2fHf+uckE1CInvFwj/6qIVG/5PDW1KxHzFatrZxAfHhqqLdwnH3U+oWW5BUAE+Sq2hwKTW9fNnKUnpXhnEXDdgIFHHauQidN4RFDVDjBEbTtUPKtR+xgiQ948xYW3FrZjQfZ/iJlr2LZmmBMo5qb3/OsctA9gDORfGDf5x61cPBoU
  template:
    metadata:
      creationTimestamp: null
      name: github
      namespace: flux-system

